### ISSUE TITLE
Tracking issue for eggShell.readJSON & Flatten / Unflatten JSON behavior

### ISSUE THREAD

**Issue by rajsite** [ni/VireoSDK#294]
- [ ] Static allocated string in EggShell_DataReadString and EggShell_DataWriteString is likely causing aborts() when Vireo is rebooted or re-run using a new user shell.

   possibly related issues: https://github.com/ni/VireoSDK/issues/275 https://github.com/ni/VireoSDK/issues/163

   [Location where static string allocation occurs in scope of type manager reference?](https://github.com/ni/VireoSDK/blob/a8df6f39d23f04e55b05faf392260e3dcf17f8d2/source/core/CEntryPoints.cpp#L180)
   [Location where type manager reference is passed on call](https://github.com/ni/VireoSDK/blob/a8df6f39d23f04e55b05faf392260e3dcf17f8d2/source/io/module_eggShell.js#L140)
   [Location where type manager is deleted on reboot](https://github.com/ni/VireoSDK/blob/a8df6f39d23f04e55b05faf392260e3dcf17f8d2/source/io/module_eggShell.js#L118)

- [ ] readJSON and Flatten / Unflatten from JSON should always return valid, safe UTF-8 strings.

   This is important for the Flatten and Unflatten JSON functions as they talk to external services

   This is also important for interoperability with other C APIs expecting to receive valid UTF-8 byte sequences when using the readJSON function. While full validation for emitting safe UTF-8 is preferable, it is likely that validation of UTF-8 structure, checks for overlong encoding, and unicode range checks are sufficient as implemented here for the JS side: https://github.com/ni/VireoSDK/blob/a8df6f39d23f04e55b05faf392260e3dcf17f8d2/source/core/module_coreHelpers.js#L88 

   related discussion: https://github.com/ni/VireoSDK/issues/283#issuecomment-311506448

- [ ] readJSON API should encode 64-bit integers as strings to improve interoperability

   It can be see how failure to do so in tests results in loss of precision: https://github.com/ni/VireoSDK/blob/a8df6f39d23f04e55b05faf392260e3dcf17f8d2/test-it/karma/publicapi/ReadJson.Test.js#L290

   This also effects data types relying on 64-bit integer values like timestamps loosing precision: https://github.com/ni/VireoSDK/blob/a8df6f39d23f04e55b05faf392260e3dcf17f8d2/test-it/karma/publicapi/ReadJson.Test.js#L386

   Treating JSON numerics as IEE754 doubles is a recommendation in both [RFC 7159](https://tools.ietf.org/html/rfc7159):
   > Since software that implements IEEE 754-2008 binary64 (double precision) numbers [IEEE754] is generally available and widely used, good interoperability can be achieved by implementations that expect no more precision or range than these provide, in the sense that implementations will approximate JSON numbers within the expected precision

   And in [RFC 7493](https://tools.ietf.org/html/rfc7493)
   > For applications that require the exact interchange of numbers with greater magnitude or precision, it is RECOMMENDED to encode them in JSON string values.

   Unfortunately the readJSON API and the Flatten/Unflatten from JSON api will have to diverge on this point as the LabVIEW API does not follow interoperability recommendations. 

- [ ] As part of the above efforts we should write a C based runner utilizing the EggShell_ReadValueString and EggShell_WriteValueString apis. 

   Part of that work should include refactoring the following tests so that the expected JSON results can be shared in both a JS and C api test suite: https://github.com/ni/VireoSDK/issues/254

- [ ] EggShell_WriteValueString tests for 2D arrays that cause the Array to grow do not behave correctly: https://github.com/ni/VireoSDK/blob/a8df6f39d23f04e55b05faf392260e3dcf17f8d2/test-it/karma/publicapi/WriteJson.Test.js#L697

- [ ] Test more around +0 vs -0 behaviors https://github.com/ni/VireoSDK/blob/a8df6f39d23f04e55b05faf392260e3dcf17f8d2/test-it/karma/publicapi/WriteJson.Test.js#L49
